version: "3"

services:
  # download client
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ${CONFIG_DIR}/transmission:/config
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - ${HOST_PORT}:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # media player
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}:/media
    environment:
      - JELLYFIN_PublishedServerUrl=${APP_URL}
    network_mode: "host"
    restart: unless-stopped

  #indexer management
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - 10200:9696
    restart: unless-stopped

  # tv show management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${MEDIA_DIR}:/data
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 10201:8989
    restart: unless-stopped

  # movie management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MEDIA_DIR}:/data
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 10202:7878
    restart: unless-stopped

  # music management
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${MEDIA_DIR}:/data
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 10203:8686
    restart: unless-stopped

  # book management
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/readarr:/config
      - ${MEDIA_DIR}:/data
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 10204:8787
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/calibre:/config
      - ${MEDIA_DIR}/books/uploads:/uploads
      - ${MEDIA_DIR}/books/library:/Calibre_Library
    ports:
      - 10205:8080 # library
      - 10206:8081 # ereader
    restart: unless-stopped

  # calibre library interface
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}/calibre-web:/config
      - ${MEDIA_DIR}/books/library:/books
    restart: unless-stopped
    depends_on:
      - calibre
    ports:
      - 10207:8083