version: "3.0"

services:
  wireguard:
    image: place1/wg-access-server
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ${CONFIG_DIR}/wireguard/data:/data
      - ${CONFIG_DIR}/wireguard/config.yaml:/config.yaml
    environment:
      - WG_ADMIN_USERNAME=admin
      - WG_ADMIN_PASSWORD=${WIREGUARD_ADMIN_PASSWORD}
      - WG_WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WG_EXTERNAL_HOST=https://${WIREGUARD_URL}
      #- WG_STORAGE=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5432/wireguard?sslmode=disable
      - WG_DNS_UPSTREAM=8.8.8.8
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
