version: "3"

services:
  # budgeting
  fireflyiii:
    container_name: fireflyiii
    image: fireflyiii/core:latest
    environment:
      APP_KEY: ${FIREFLY_APP_KEY}
      TRUSTED_PROXIES: "**"
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_DATABASE: fireflyiii
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/fireflyiii:/var/www/html/storage/upload
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fireflyiii.rule=Host(`${FIREFLY_URL}`)"
      - "traefik.http.routers.fireflyiii.entrypoints=websecure"
      - "traefik.http.routers.fireflyiii.tls.certresolver=tlsresolver"
      - "traefik.http.services.fireflyiii.loadbalancer.server.port=8080"
      - "traefik.http.routers.fireflyiii.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  # tasks
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja:latest
    environment:
      VIKUNJA_DATABASE_HOST: ${DATABASE_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: ${DATABASE_USER}
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_HOST: ${MAILER_HOST}
      VIKUNJA_MAILER_PORT: ${MAILER_PORT}
      VIKUNJA_MAILER_USERNAME: ${MAILER_USERNAME}
      VIKUNJA_MAILER_PASSWORD: ${MAILER_PASSWORD}
      VIKUNJA_SERVICE_TIMEZONE: ${TIMEZONE}
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_JWT_SECRET}
      VIKUNJA_SERVICE_PUBLICURL: https://${VIKUNJA_URL}
    volumes:
      - ${CONFIG_DIR}/vikunja/files:/app/vikunja/files
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(`${VIKUNJA_URL}`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.tls.certresolver=tlsresolver"
      - "traefik.http.routers.vikunja.middlewares=authelia@docker"
      - "traefik.http.services.vikunja.loadbalancer.server.port=3456"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
