version: "3.9"

services:
  myip:
    image: "jason5ng32/myip:latest"
    container_name: myip
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myip.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.myip.entrypoints=websecure"
      - "traefik.http.routers.myip.tls.certresolver=tlsresolver"
      - "traefik.http.services.myip.loadbalancer.server.port=18966"
      - "traefik.http.routers.myip.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
