version: "3.9"
services:
  hoppscotch:
    image: hoppscotch/hoppscotch
    container_name: hoppscotch
    ports:
      - 3170:3170 # backend
      - 3100:3100 # admin
      - 3000:3000 # frontend
    environment:
      # --Backend Configs--
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT:-5432}/${DBNAME:-hoppscotch}"
      HOPP_AIO_ALTERNATE_PORT: ${HOPP_AIO_ALTERNATE_PORT:-80}
      # Auth Token Configs
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_SALT_COMPLEXITY: ${TOKEN_SALT_COMPLEXITY:-10}
      MAGIC_LINK_TOKEN_VALIDITY: ${MAGIC_LINK_TOKEN_VALIDITY:-3}
      REFRESH_TOKEN_VALIDITY: ${REFRESH_TOKEN_VALIDITY:-604800000}
      ACCESS_TOKEN_VALIDITY: ${ACCESS_TOKEN_VALIDITY:-86400000}
      SESSION_SECRET: ${SESSION_SECRET}
      ALLOW_SECURE_COOKIES: ${ALLOW_SECURE_COOKIES:-true}
      DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
      # App Domain Configs
      REDIRECT_URL: ${REDIRECT_URL:-http://localhost:3000}
      WHITELISTED_ORIGINS: "http://localhost:3170,http://localhost:3000,http://localhost:3100"
      VITE_ALLOWED_AUTH_PROVIDERS: ${VITE_ALLOWED_AUTH_PROVIDERS:-EMAIL}
      # Mailer Configs
      MAILER_SMTP_ENABLE: ${MAILER_SMTP_ENABLE:-true}
      MAILER_USE_CUSTOM_CONFIGS: ${MAILER_USE_CUSTOM_CONFIGS:-true}
      MAILER_ADDRESS_FROM: ${MAILER_ADDRESS_FROM}
      MAILER_SMTP_HOST: ${MAILER_SMTP_HOST}
      MAILER_SMTP_PORT: ${MAILER_SMTP_PORT:-587}
      MAILER_SMTP_SECURE: ${MAILER_SMTP_SECURE:-true}
      MAILER_SMTP_USER: ${MAILER_SMTP_USER}
      MAILER_SMTP_PASSWORD: ${MAILER_SMTP_PASSWORD}
      MAILER_TLS_REJECT_UNAUTHORIZED: ${MAILER_TLS_REJECT_UNAUTHORIZED:-true}
      # Rate Limit Configs
      RATE_LIMIT_TTL: ${RATE_LIMIT_TTL:-60}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
      # --Frontend Configs--
      VITE_BASE_URL: https://${APP_URL}
      VITE_SHORTCODE_BASE_URL: https://${APP_URL}
      VITE_ADMIN_URL: https://${APP_URL}/admin
      VITE_BACKEND_GQL_URL: https://${APP_URL}/graphql
      VITE_BACKEND_WS_URL: wss://${APP_URL}/graphql
      VITE_BACKEND_API_URL: https://${APP_URL}/v1
      VITE_APP_TOS_LINK: ${VITE_APP_TOS_LINK:-https://docs.hoppscotch.io/support/terms}
      VITE_APP_PRIVACY_POLICY_LINK: ${VITE_APP_PRIVACY_POLICY_LINK:-https://docs.hoppscotch.io/support/privacy}
      ENABLE_SUBPATH_BASED_ACCESS: true
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoppscotch.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.hoppscotch.entrypoints=websecure"
      - "traefik.http.routers.hoppscotch.tls.certresolver=tlsresolver"
      - "traefik.http.routers.hoppscotch.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
