version: "3"

services:
  server1:
    container_name: minecraft${SERVER_1_INSTANCE_MODIFIER}
    image: itzg/minecraft-server
    volumes:
      - ${CONFIG_DIR}/minecraft${SERVER_1_INSTANCE_MODIFIER}/data:/data
      - ${CONFIG_DIR}/minecraft${SERVER_1_INSTANCE_MODIFIER}/modpacks:/modpacks
    environment:
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/${SERVER_1_MODPACK}

      EULA: "true"
      DIFFICULTY: normal

      INIT_MEMORY: 1G
      MAX_MEMORY: 16G
    restart: unless-stopped

  server2:
    container_name: minecraft${SERVER_2_INSTANCE_MODIFIER}
    image: itzg/minecraft-server
    volumes:
      - ${CONFIG_DIR}/minecraft${SERVER_2_INSTANCE_MODIFIER}/data:/data
    environment:
      EULA: "true"
      DIFFICULTY: normal

      INIT_MEMORY: 1G
      MAX_MEMORY: 8G
    restart: unless-stopped

  router:
    container_name: mc_router
    image: itzg/mc-router
    ports:
      - 25565:25565
    command: --mapping=mc${SERVER_1_INSTANCE_MODIFIER}.${SERVER_PROXY_URL}=server1:25565,mc${SERVER_2_INSTANCE_MODIFIER}.${SERVER_PROXY_URL}=server2:25565
    restart: unless-stopped
