version: '2'

services:
  server:
    container_name: minecraft
    image: itzg/minecraft-server
    volumes:
    - /opt/minecraft/data:/data
    - /opt/minecraft/modpacks:/modpacks
    environment:
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Enigmatica6Server-0.2.17.zip
      
      EULA: "true"
      DIFFICULTY: normal
      
      INIT_MEMORY: 1G
      MAX_MEMORY: 8G
    ports:
      - 25565:25565
    restart: unless-stopped