version: "3"

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ${CONFIG_DIR}/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ${CONFIG_DIR}/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
