version: '3.3'

services:
  app:
    container_name: fireflyiii
    image: fireflyiii/core:latest
    environment: 
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      TRUSTED_PROXIES: '**'
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /media/share/fireflyiii:/var/www/html/storage/upload
    ports:
      - 5550:8080
    restart: unless-stopped
