version: '3.3'

services:
  app:
    container_name: fireflyiii
    image: fireflyiii/core:latest
    environment: 
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      TRUSTED_PROXIES: '**'
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "America/New_York"
    volumes:
      - /opt/fireflyiii:/var/www/html/storage/upload
    ports:
      - 5550:8080
    restart: unless-stopped

  cron:
    container_name: fireflyiii_cron
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- ${APP_URL}/api/v1/cron/${COMMAND_LINE_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    restart: unless-stopped
