version: '3'
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    hostname: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: ${LDAP_ORGANIZATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}.${LDAP_TLD}
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "never"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ${CONFIG_DIR}/openldap/var_lib_ldap:/var/lib/ldap
      - ${CONFIG_DIR}/openldap/etc_ldap_slapd.d:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    restart: unless-stopped

  openldap-ui:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    volumes:
      - ${CONFIG_DIR}/openldap/ui:/var/www/phpldapadmin
    ports:
      - "8785:80"
    depends_on:
      - openldap
    restart: unless-stopped