version: "3.9"

services:
  app:
    image: cfu288/mere-medical:latest
    container_name: mere-medical
    environment:
      # - ONPATIENT_CLIENT_ID=${ONPATIENT_CLIENT_ID}
      # - ONPATIENT_CLIENT_SECRET=${ONPATIENT_CLIENT_SECRET}
      - EPIC_CLIENT_ID=${EPIC_CLIENT_ID}
      - EPIC_SANDBOX_CLIENT_ID=${EPIC_SANDBOX_CLIENT_ID}
      # - CERNER_CLIENT_ID=${CERNER_CLIENT_ID}
      # - VERADIGM_CLIENT_ID=${VERADIGM_CLIENT_ID}
      - PUBLIC_URL=https://${APP_URL}
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mere-medical.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.mere-medical.entrypoints=websecure"
      - "traefik.http.routers.mere-medical.tls.certresolver=tlsresolver"
      - "traefik.http.routers.mere-medical.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
