version: "3"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DATABASE_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DATABASE_NAME}
      - DB_POSTGRESDB_USER=${DATABASE_USER}
      - DB_POSTGRESDB_PASSWORD=${DATABASE_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${USERNAME}
      - N8N_BASIC_AUTH_PASSWORD=${PASSWORD}
      - WEBHOOK_URL=${APP_URL}
      - TZ=America/New_York
    ports:
      - 5678:5678
    volumes:
      - /opt/n8n:/home/node/.n8n
    restart: unless-stopped