services:
  palworld:
    image: thijsvanloef/palworld-server-docker
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
      - PORT=8211
      - PLAYERS=16
      - MULTITHREADING=FALSE
      - COMMUNITY=false
      - SERVER_PASSWORD="${SERVER_PASSWORD}"
      - SERVER_NAME="${SERVER_NAME}"
      - ADMIN_PASSWORD="${ADMIN_PASSWORD}"
    volumes:
      - ${CONFIG_DIR}/palworld:/palworld/
