version: "3"

networks:
  public:
    driver: bridge

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/providers:/config
    networks:
      - public
    command:
      - "--api.insecure"
      - "--accesslog"
      - "--entrypoints.web.Address=:80"
      - "--entrypoints.websecure.Address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.defaultRule=Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
      - "--providers.file.directory=/config"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.tlsresolver.acme.tlschallenge"
      - "--certificatesresolvers.tlsresolver.acme.email=${TLS_EMAIL}"
      - "--certificatesresolvers.tlsresolver.acme.storage=acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_frontend.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.traefik_frontend.entrypoints=websecure"
      - "traefik.http.routers.traefik_frontend.tls.certresolver=tlsresolver"
      - "traefik.http.services.traefik_frontend.loadbalancer.server.port=8080"
      
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${TRAEFIK_AUTH_PROXY_URL}/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      
      - "traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic"
      - "traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email"
      
      - "traefik.http.routers.traefik_frontend.middlewares=authelia-basic@docker"
    depends_on:
      - authelia
    restart: unless-stopped
    
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /opt/authelia:/config
    environment:
      - TZ=America/New_York
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`${TRAEFIK_AUTH_PROXY_URL}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=tlsresolver"
    expose:
      - 9091
    restart: unless-stopped
    
