- alias: Turn Office Lights Off
  trigger:
    - platform: mqtt
      topic: "lights/office"
      payload: "off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.cabinet_lamp

- alias: Turn Office Lights On
  trigger:
    - platform: mqtt
      topic: "lights/office"
      payload: "on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.cabinet_lamp

# works with any CSS3 color https://www.w3schools.com/colors/colors_names.asp
- alias: Set Office Light Color
  trigger:
    - platform: mqtt
      topic: "lights/office/color"
  action:
    - service: light.turn_on
      target:
        entity_id: light.cabinet_lamp
      data:
        color_name: "{{ trigger.payload }}"
