- alias: Turn Office Lights Off
  trigger:
    - platform: mqtt
      topic: "home/office/lights/off"
  action:
    - service: light.turn_off
      target:
        entity_id: light.office

- alias: Turn Office Lights On
  trigger:
    - platform: mqtt
      topic: "home/office/lights/on"
  action:
    - service: light.turn_on
      target:
        entity_id: light.office
      data:
        color_name: "white"

# payload must be a valid CSS3 color name: https://www.w3.org/wiki/CSS/Properties/color/keywords
- alias: Set Office Light Color by Name
  trigger:
    - platform: mqtt
      topic: "home/office/lights/color/name"
  action:
    - service: light.turn_on
      target:
        entity_id: light.office
      data:
        color_name: "{{ trigger.payload }}"

# payload must be in the format of [255,255,255]
- alias: Set Office Light Color by RGB
  trigger:
    - platform: mqtt
      topic: "home/office/lights/color/rgb"
  action:
    - service: light.turn_on
      target:
        entity_id: light.office
      data:
        rgb_color: "{{ trigger.payload }}"
