
# Loads default set of integrations. Do not remove.
default_config:

# Loads cards installed with HACS
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module

# Text to speech
tts:
  - platform: google_translate

# Reverse proxy
http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - $PROXY_HOST

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
