version: "3"

services:
  web:
    image: homeassistant/home-assistant:stable
    container_name: home_assistant
    ports:
      - 8123:8123
    volumes:
      - /media/share/homeassistant:/config
    environment:
      - TZ=America/New_York
    restart: unless-stopped
