version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: '${PASSWORD}'
      VIRTUAL_HOST: '${TRAEFIK_PROXY_URL}'
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112;1.1.1.1
      DNSSEC: 'true'
      ServerIP: ${HOST_IP}
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.0.100
      DHCP_END: 192.168.0.199
      DHCP_ROUTER: 192.168.0.1
      DHCP_LEASETIME: 6
      WEBTHEME: default-dark
      PIHOLE_DOMAIN: public
    volumes:
      - '/opt/pihole/etc:/etc/pihole'
      - '/opt/pihole/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    networks:
      - public
      - backend:
          - ipv4_address: '172.31.0.100'
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=tlsresolver"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    depends_on:
      - dhcphelper
    restart: unless-stopped

  dhcphelper:
    image: noamokman/dhcp-helper
    container_name: dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}