version: "3.5"

services:
  # tv, movies, music
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}:/media
    environment:
      - JELLYFIN_PublishedServerUrl=https://${JELLYFIN_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "host" # port 8096
    devices: # pass iGPU for transcoding
      - /dev/dri
    restart: unless-stopped

  jellyfin-vue:
    image: ghcr.io/jellyfin/jellyfin-vue:stable-rc
    container_name: jellyfin-vue
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin-vue.rule=Host(`${JELLYFIN_VUE_URL}`)"
      - "traefik.http.routers.jellyfin-vue.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-vue.tls.certresolver=tlsresolver"
      - "traefik.http.routers.jellyfin-vue.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  # books
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - ${CONFIG_DIR}/kavita:/kavita/config
      - ${MEDIA_DIR}:/media
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`${KAVITA_URL}`)"
      - "traefik.http.routers.kavita.entrypoints=websecure"
      - "traefik.http.routers.kavita.tls.certresolver=tlsresolver"
      - "traefik.http.routers.kavita.middlewares=authelia@docker"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  # roms
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-America/New_York}
    volumes:
      - ${CONFIG_DIR}/emulatorjs/config:/config
      - ${CONFIG_DIR}/emulatorjs/data:/data
      - ${ROMS_DIR}/gb:/data/gb/roms
      - ${ROMS_DIR}/gba:/data/gba/roms
      - ${ROMS_DIR}/gbc:/data/gbc/roms
      - ${ROMS_DIR}/nds:/data/nds/roms
      - ${ROMS_DIR}/n64:/data/n64/roms
      - ${ROMS_DIR}/snes:/data/snes/roms
    ports:
      - 17500:3000 # internal configuration interface
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emulatorjs.rule=Host(`${EMULATORJS_URL}`)"
      - "traefik.http.routers.emulatorjs.entrypoints=websecure"
      - "traefik.http.routers.emulatorjs.tls.certresolver=tlsresolver"
      - "traefik.http.routers.emulatorjs.middlewares=authelia@docker"
      - "traefik.http.services.emulatorjs.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
