version: "3.9"

services:
  it-tools:
    container_name: it-tools
    image: "corentinth/it-tools:latest"
    networks:
      - postgres
      - public
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.devtools.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.devtools.entrypoints=websecure"
      - "traefik.http.routers.devtools.tls.certresolver=tlsresolver"
      - "traefik.http.services.devtools.loadbalancer.server.port=80"
      - "traefik.http.routers.devtools.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
