version: "3"

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=8443
    volumes:
      - ${CONFIG_DIR}/kasm/data:/opt
      - ${CONFIG_DIR}/kasm/profiles:/profiles
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data
    ports:
      - 19000:3000
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kasm.rule=Host(`${WORKSPACE_URL}`)"
      - "traefik.http.routers.kasm.entrypoints=websecure"
      - "traefik.http.routers.kasm.tls.certresolver=tlsresolver"
      - "traefik.http.services.kasm.loadbalancer.server.port=8443"
      - "traefik.http.services.kasm.loadbalancer.server.scheme=https"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped