version: "3"

networks:
  public:
    name: ${TRAEFIK_PUBLIC_NETWORK}
    external: true

services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=8443
    volumes:
      - ${CONFIG_DIR}/kasm/data:/opt
      - ${CONFIG_DIR}/kasm/profiles:/profiles
      # - /dev/input:/dev/input # gamepad passthrough
      # - /run/udev/data:/run/udev/data # gamepad passthrough
    ports:
      - 8443:8443
      - 19000:3000
    networks:
      - public
    # deploy: # pass NVIDIA gpu to container
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: unless-stopped
