version: '3'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /opt/rabbitmq/data/:/var/lib/rabbitmq/
        - /opt/rabbitmq/log/:/var/log/rabbitmq