version: '3'

networks:
  public:
    driver: bridge

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/networking/traefik.yml:/traefik.yml
      - /opt/networking/letsencrypt:/letsencrypt
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_frontend.rule=Host(`${TRAEFIK_DASH_PROXY_URL}`)"
      - "traefik.http.routers.traefik_frontend.entrypoints=websecure"
      - "traefik.http.routers.traefik_frontend.tls.certresolver=tlsresolver"
      - "traefik.http.services.traefik_frontend.loadbalancer.server.port=8080"
    restart: unless-stopped