version: '2'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - ${HOST_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config/traefik/traefik.yml:/traefik.yml
      - /config/traefik/letsencrypt:/letsencrypt
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.tls.certresolver=${TRAEFIK_TLS_RESOLVER}"
      - "traefik.http.services.${TRAEFIK_SERVICE_NAME}.loadbalancer.server.port=${HOST_PORT}"
    restart: unless-stopped

networks:
  public: 