version: '2'

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config/traefik/traefik.yml:/traefik.yml
      - /config/traefik/acme.json:/acme.json
    networks:
      - public
    restart: unless-stopped

networks:
  public: 