providers:
        docker:
                exposedByDefault: false
                defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

entrypoints:
        web:
                address: ":80"
                http:
                        redirections:
                                entrypoint:
                                        to: websecure
                                        scheme: https
        websecure:
                address: ":443"

certificatesresolvers:
        tlsresolver:
                acme:
                        tlschallenge: true
                        email: "your@email.com"
                        storage: "/letsencrypt/acme.json"

api:
        insecure: true

metrics:
        prometheus: {}

accessLog: {}
