providers:
        docker:
                exposedByDefault: false
                defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

entrypoints:
        web:
                address: ":80"

api:
        insecure: true
