version: "3.8"

services:
  steam-headless:
    image: josh5/steam-headless:latest
    container_name: steam-headless
    restart: unless-stopped
    ## NOTE: This config uses privileged to access to host to be able to access the required devices
    privileged: true
    shm_size: ${SHM_SIZE:-2G}
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288

    # NETWORK:
    ## NOTE:  With this configuration, if we do not use the host network, then physical device input
    ##        is not possible and your USB connected controllers will not work in steam games.
    network_mode: host
    hostname: ${NAME:-SteamHeadless}
    extra_hosts:
      - "${NAME:-SteamHeadless}:127.0.0.1"

    # ENVIRONMENT:
    ## Read all config variables from the .env file
    environment:
      # System
      - TZ=${TIMEZONE:-America/New_York}
      - USER_LOCALES=${USER_LOCALES:-"en_US.UTF-8 UTF-8"}
      - DISPLAY=${DISPLAY:-:55}

      # User
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - USER_PASSWORD=${USER_PASSWORD}

      # Mode
      - MODE=${MODE:-primary}

      # Web UI
      - WEB_UI_MODE=${WEB_UI_MODE:-vnc}
      - ENABLE_VNC_AUDIO=${ENABLE_VNC_AUDIO:-true}
      - PORT_NOVNC_WEB=${PORT_NOVNC_WEB:-8083}
      # - NEKO_NAT1TO1=${NEKO_NAT1TO1}

      # Steam
      - ENABLE_STEAM=${ENABLE_STEAM:-true}
      - STEAM_ARGS=${STEAM_ARGS:-"-silent"}

      # Sunshine
      - ENABLE_SUNSHINE=${ENABLE_SUNSHINE:-false}
      # - SUNSHINE_USER=${SUNSHINE_USER}
      # - SUNSHINE_PASS=${SUNSHINE_PASS}

      # Xorg
      - ENABLE_EVDEV_INPUTS=${ENABLE_EVDEV_INPUTS:-true}
      - FORCE_X11_DUMMY_CONFIG=${FORCE_X11_DUMMY_CONFIG:-false}

      # Nvidia specific config
      # - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}
      # - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      # - NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION}

    # VOLUMES:
    volumes:
      # The location of your home directory.
      - ${CONFIG_DIR}/steam-headless/home:/home/default/:rw

      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      - ${GAMES_DIR}/:/mnt/games/:rw

      # The Xorg socket.
      - ${CONFIG_DIR}/steam-headless/.X11-unix/:/tmp/.X11-unix/:rw

      # Pulse audio socket.
      - ${CONFIG_DIR}/steam-headless/pulse/:/tmp/pulse/:rw
