version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13.5
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       -${CONFIG_DIR}/postgres/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - 5050:80
    volumes:
       - ${CONFIG_DIR}/postgres/pgadmin_data:/var/lib/pgadmin
       - ${CONFIG_DIR}/postgres/backup:/backup
    restart: unless-stopped
