version: "3.5"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=${APP_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "host" # port 8096
    devices: # pass iGPU for transcoding
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    restart: unless-stopped

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    ports:
      - 5690:5690
    volumes:
      - ${CONFIG_DIR}/wizarr/database:/data/database
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  jellystat:
    container_name: jellystat
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_IP: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    volumes:
      - ${CONFIG_DIR}/jellystat/backup-data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

volumes:
  media:
    name: remote_media
    driver: local
    driver_opts:
      type: cifs
      device: ${TARGET_SHARE}
      o: addr=${SHARE_HOSTNAME},username=${SHARE_USER},password=${SHARE_PASS},file_mode=0777,dir_mode=0777
