version: "3.5"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ${CONFIG_DIR}/jellyfin/config:/config
      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}:/media
    environment:
      - JELLYFIN_PublishedServerUrl=${APP_URL}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: "host" # port 8096
    devices: # pass iGPU for transcoding
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped