version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - /media/share/mosquitto/data:/mosquitto/data
      - /media/share/mosquitto/log:/mosquitto/log
      - /media/share/mosquitto/config:/mosquitto/config
    restart: unless-stopped