version: "3"

services:
  web:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home_assistant
    ports:
      - 8123:8123
    volumes:
      - ${CONFIG_DIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TIMEZONE:-America/New_York}
    network_mode: host # allows home assistant to detect devices on the network
    privileged: true
    restart: unless-stopped
