version: "3"

services:
  web:
    image: homeassistant/home-assistant:stable
    container_name: home_assistant
    volumes:
      - /opt/homeassistant:/config
    environment:
      - TZ=America/New_York
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_homeassistant.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.web_homeassistant.entrypoints=websecure"
      - "traefik.http.routers.web_homeassistant.tls.certresolver=tlsresolver"
      - "traefik.http.services.web_homeassistant.loadbalancer.server.port=8123"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
