apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${VOLUME_NAME}
  labels:
    bucket: shared
spec:
  capacity:
    storage: ${VOLUME_SIZE}
  volumeMode: Filesystem
  storageClassName: slow
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_IP_ADDRESS}
    path: ${NFS_PATH}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${VOLUME_SIZE}
  selector:
    matchLabels:
      bucket: shared
