version: "3"

volumes:
  jenkins_data: {}

services:
  jenkins:
    build:
      context: ./
    container_name: jenkins
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
