version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - public
    volumes:
      - ${CONFIG_DIR}/homepage/config:/app/config
      - ${CONFIG_DIR}/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service-dashboard.rule=Host(`${SERVICE_DASHBOARD_URL}`)"
      - "traefik.http.routers.service-dashboard.entrypoints=websecure"
      - "traefik.http.routers.service-dashboard.tls.certresolver=tlsresolver"
      - "traefik.http.services.service-dashboard.loadbalancer.server.port=3000"
      - "traefik.http.routers.service-dashboard.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
