version: "3"

volumes:
  db_data: {}

services:
  cloudbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8080:8978
    volumes:
      - db_data:/opt/cloudbeaver/workspace
    restart: unless-stopped
