version: "3.7"

services:
  traggo:
    image: traggo/server:latest
    container_name: traggo
    environment:
      TRAGGO_DEFAULT_USER_NAME: ${ADMIN_USER_NAME:-admin}
      TRAGGO_DEFAULT_USER_PASS: ${ADMIN_USER_PASS:-admin}
    volumes:
      - ${CONFIG_DIR}/traggo:/opt/traggo/data
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traggo.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.traggo.entrypoints=websecure"
      - "traefik.http.routers.traggo.tls.certresolver=tlsresolver"
      - "traefik.http.services.traggo.loadbalancer.server.port=3030"
      - "traefik.http.routers.traggo.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
