version: "3.7"
services:
  the-forest-dedicated-server:
    container_name: the-forest-dedicated-server
    image: jammsen/the-forest-dedicated-server:latest
    restart: unless-stopped
    environment:
      SERVER_STEAM_ACCOUNT_TOKEN: ${STEAM_ACCOUNT_TOKEN}
      ALWAYS_UPDATE_ON_START: 1
    ports:
      - 8766:8766/tcp
      - 8766:8766/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - ${CONFIG_DIR}/the_forest/steamcmd:/steamcmd
      - ${CONFIG_DIR}/the_forest/game:/theforest
      - ${CONFIG_DIR}/the_forest/winedata:/winedata
