version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TIMEZONE:-America/New_York}
    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - ${CONFIG_DIR}/ntfy/cache:/var/cache/ntfy
      - ${CONFIG_DIR}/ntfy/etc:/etc/ntfy
    ports:
      - 8080:80
    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://${HOST}:8080/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
