version: "3.3"

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TIMEZONE:-America/New_York}
      - NTFY_BASE_URL=https://${APP_URL}
      - NTFY_BEHIND_PROXY=true
      - NTFY_LISTEN_HTTP=:8080
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_CACHE_DURATION=${CACHE_DURATION:-72h}
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ATTACHMENT_EXPIRY_DURATION=${CACHE_DURATION:-72h}
      - NTFY_AUTH_FILE=/var/cache/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_ENABLE_LOGIN=true
    user: ${PUID:-1000}:${PGID:-1000}
    volumes:
      - ${CONFIG_DIR}/ntfy/cache:/var/cache/ntfy
      - ${CONFIG_DIR}/ntfy/etc:/etc/ntfy
    ports:
      - 8080:8080
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://${HOST}:8080/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.tls.certresolver=tlsresolver"
      - "traefik.http.services.ntfy.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
