version: "3"

services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-America/New_York}
    volumes:
      - ${CONFIG_DIR}/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped