version: "3"

services:
  trilium:
    container_name: trilium
    image: triliumnext/notes:latest
    environment:
      - TRILIUM_DATA_DIR=/data
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    ports:
      - 5600:8080
    volumes:
      - ${CONFIG_DIR}/trilium:/data
    restart: unless-stopped
