version: "3"

services:
  trilium:
    container_name: trilium
    image: triliumnext/trilium:latest
    environment:
      - TRILIUM_DATA_DIR=/data
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      # OpenID Connect Configuration
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHBASEURL=${TRILIUM_OAUTH_BASE_URL}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTID=${TRILIUM_OAUTH_CLIENT_ID}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTSECRET=${TRILIUM_OAUTH_CLIENT_SECRET}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERBASEURL=${TRILIUM_OAUTH_ISSUER_BASE_URL}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERNAME=${TRILIUM_OAUTH_ISSUER_NAME}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERICON=${TRILIUM_OAUTH_ISSUER_ICON}
    ports:
      - 5600:8080
    volumes:
      - ${CONFIG_DIR}/trilium:/data
    restart: unless-stopped
