version: "3"

services:
  trilium:
    container_name: trilium
    image: triliumnext/trilium:latest
    environment:
      - TRILIUM_DATA_DIR=/data
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      # OpenID Connect Configuration
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHBASEURL=${TRILIUM_OAUTH_BASE_URL}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTID=${TRILIUM_OAUTH_CLIENT_ID}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTSECRET=${TRILIUM_OAUTH_CLIENT_SECRET}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERBASEURL=${TRILIUM_OAUTH_ISSUER_BASE_URL}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERNAME=${TRILIUM_OAUTH_ISSUER_NAME}
      - TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERICON=${TRILIUM_OAUTH_ISSUER_ICON}
    volumes:
      - ${CONFIG_DIR}/trilium:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilium.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.trilium.entrypoints=websecure"
      - "traefik.http.routers.trilium.tls.certresolver=tlsresolver"
      - "traefik.http.services.trilium.loadbalancer.server.port=8080"
      - "traefik.http.routers.trilium.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
