version: "3"

services:
  trilium:
    container_name: trilium
    image: triliumnext/notes:latest
    environment:
      - TRILIUM_DATA_DIR=/data
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    volumes:
      - ${CONFIG_DIR}/trilium:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trilium.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.trilium.entrypoints=websecure"
      - "traefik.http.routers.trilium.tls.certresolver=tlsresolver"
      - "traefik.http.services.trilium.loadbalancer.server.port=8080"
      - "traefik.http.routers.trilium.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
