version: "3.9"

services:
  web-check:
    image: lissy93/web-check
    container_name: web-check
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-check.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.web-check.entrypoints=websecure"
      - "traefik.http.routers.web-check.tls.certresolver=tlsresolver"
      - "traefik.http.services.web-check.loadbalancer.server.port=3000"
      - "traefik.http.routers.web-check.middlewares=authelia@docker"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
