version: "3"

services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
      - USER=${USERNAME}
      - PASS=${PASSWORD}
      - WHITELIST=${IP_WHITELIST}
    volumes:
      - ${CONFIG_DIR}:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${WATCH_DIR}:/watch
    ports:
      - ${HOST_PORT}:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped