version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /opt/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=tlsresolver"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    privileged: true
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}