services:
  ersatztv:
    container_name: ersatztv
    image: jasongdove/ersatztv:latest-vaapi
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/ersatztv:/root/.local/share/ersatztv
      # - ${MEDIA_DIR}:/media:ro # for local media
      - type: tmpfs
        target: /root/.local/share/etv-transcode
    ports:
      - "8409:8409"
    devices: # pass iGPU for transcoding
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - TZ=${TIMEZONE:-America/New_York}
