version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    networks:
      - postgres
      - public
    labels:
      - "traefik.enable=true"
      
      # frontend
      - "traefik.http.routers.postgres_pgadmin.service=postgres_pgadmin"
      - "traefik.http.routers.postgres_pgadmin.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.postgres_pgadmin.entrypoints=websecure"
      - "traefik.http.routers.postgres_pgadmin.tls.certresolver=tlsresolver"
      - "traefik.http.services.postgres_pgadmin.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}

volumes:
    postgres:
    pgadmin: