name: Publish KASM Desktop Dev Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  multi_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./services/kasm/workspaces/desktop-dev
          file: ./services/kasm/workspaces/desktop-dev/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kasm-desktop-dev:latest
            ghcr.io/${{ github.repository_owner }}/kasm-desktop-dev:${{ github.sha }}
