version: "3"

services:
  server:
    image: lloesche/valheim-server
    container_name: valheim
    volumes:
      - ${CONFIG_DIR}/valheim/config:/config
      - ${CONFIG_DIR}/valheim/data:/opt/valheim
    ports:
      - 2456-2457:2456-2457/udp
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SERVER_PASS=${SERVER_PASSWORD}
      - TZ=${TIMEZONE}
    restart: always
