version: "3"

services:
  vikunja:
    container_name: vikunja
    image: vikunja/vikunja:latest
    environment:
      VIKUNJA_DATABASE_HOST: ${DATABASE_HOST}
      VIKUNJA_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: ${DATABASE_USER}
      VIKUNJA_DATABASE_DATABASE: ${DATABASE_NAME}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: 0
      VIKUNJA_MAILER_ENABLED: 1
      VIKUNJA_MAILER_HOST: ${MAILER_HOST}
      VIKUNJA_MAILER_PORT: ${MAILER_PORT}
      VIKUNJA_MAILER_USERNAME: ${MAILER_USERNAME}
      VIKUNJA_MAILER_PASSWORD: ${MAILER_PASSWORD}
      VIKUNJA_SERVICE_TIMEZONE: America/New_York
      VIKUNJA_SERVICE_JWTSECRET: ${JWT_SECRET}
      VIKUNJA_SERVICE_PUBLICURL: ${APP_URL}
    volumes:
      - ${CONFIG_DIR}/vikunja/files:/app/vikunja/files
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vikunja.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.vikunja.entrypoints=websecure"
      - "traefik.http.routers.vikunja.tls.certresolver=tlsresolver"
      - "traefik.http.services.vikunja.loadbalancer.server.port=3456"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}
